name: "Test and lint"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./src
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: "actions/checkout@v5"

      - name: Install uv and set the Python version
        uses: "astral-sh/setup-uv@v6"
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install package in editable mode
        run: uv pip install -e .

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests

      - name: Run ruff
        run: uv run ruff check

      - name: Run formatting
        run: uv run ruff format --check --diff

      - name: Run mypy
        run: uv run mypy .
